name: Run Analog Sensor Simulation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib streamlit pytest

      - name: Run Ngspice Simulation (Docker)
        run: |
          docker build -t vlsi-sensor .
          docker run --rm -v ${{ github.workspace }}:/app vlsi-sensor



      - name: Upload Output CSV
        uses: actions/upload-artifact@v4
        with:
          name: ptat-output
          path: ptat_output.csv